# Generated by Django 5.2.6 on 2025-09-14 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='certifications',
            field=models.TextField(blank=True, help_text='Teaching certifications, degrees, etc.'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='experience_level',
            field=models.CharField(choices=[('beginner', 'Less than 1 year'), ('intermediate', '1-3 years'), ('experienced', '3-5 years'), ('expert', '5+ years')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='languages_spoken',
            field=models.CharField(default='English', help_text='Languages you can teach in', max_length=200),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='prefers_in_person',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='prefers_online',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='specializations',
            field=models.TextField(blank=True, help_text='Special areas of expertise'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='teaching_philosophy',
            field=models.TextField(blank=True, help_text='Your approach to teaching', max_length=1000),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='teaching_style',
            field=models.CharField(choices=[('visual', 'Visual Learning'), ('hands_on', 'Hands-on Practice'), ('discussion', 'Discussion Based'), ('structured', 'Structured Lessons'), ('flexible', 'Flexible Approach')], default='flexible', max_length=20),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='travel_distance',
            field=models.IntegerField(default=0, help_text='Max km willing to travel (0 for online only)'),
        ),
        migrations.AddField(
            model_name='user',
            name='grade_level',
            field=models.CharField(blank=True, help_text='Grade 9, Grade 12, University, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.TextField(blank=True, help_text='Hobbies, interests, goals', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='is_profile_public',
            field=models.BooleanField(default=True, help_text='Show profile to other users'),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, help_text='City, Province', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(blank=True, help_text='School or University name', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='social_instagram',
            field=models.CharField(blank=True, help_text='Instagram username', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='social_linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
