# Generated by Django 5.2.6 on 2025-09-20 18:23

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tutorprofile_certifications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorprofile',
            name='hourly_rate',
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='commitment_level',
            field=models.CharField(choices=[('casual', 'Casual (1-2 hours/week)'), ('regular', 'Regular (3-5 hours/week)'), ('dedicated', 'Dedicated (6-10 hours/week)'), ('intensive', 'Intensive (10+ hours/week)')], default='regular', help_text='How much time can you commit weekly?', max_length=20),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='motivation',
            field=models.TextField(blank=True, help_text='Why do you want to volunteer as a tutor?', max_length=1000),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='volunteer_hours_completed',
            field=models.PositiveIntegerField(default=0, help_text='Total volunteer hours completed'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='volunteer_hours_goal',
            field=models.PositiveIntegerField(default=10, help_text='Monthly volunteer hours goal'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='volunteer_start_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2025, 9, 20, 18, 23, 6, 203133, tzinfo=datetime.timezone.utc), help_text='When they started volunteering'),
            preserve_default=False,
        ),
    ]
