# Generated by Django 5.2.6 on 2025-09-30 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_tutorprofile_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Admin must approve before tutor can access platform'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Optional reason if application is rejected'),
        ),
    ]
